### ISSUE TITLE
 I can add a responsive footer in the webpage

### ISSUE THREAD

**Issue by aayush-506** [narasimha-1511/Blog_with_Express_JS#4]
please assign me this issue

**Comment by narasimha-1511** [comment]
Go on @aayush-506

**Comment by aayush-506** [comment]
can you please add Hacktoberfest label to it.....

**Comment by narasimha-1511** [comment]
Ha Done .. If you Like the Project Star the repo..

**Comment by aayush-506** [comment]
I have pushed a Pull Request which contains the footer.
please have a look on it.
and Response ASAP...
